/**
 * Application Error Codes
 */

export enum ErrorCode {
    // LLM Errors
    LLM_GENERATION_FAILED = 'LLM_GENERATION_FAILED',
    LLM_MODEL_NOT_READY = 'LLM_MODEL_NOT_READY',
    LLM_CONTEXT_TOO_LONG = 'LLM_CONTEXT_TOO_LONG',

    // Storage Errors
    STORAGE_READ_FAILED = 'STORAGE_READ_FAILED',
    STORAGE_WRITE_FAILED = 'STORAGE_WRITE_FAILED',
    STORAGE_CLEAR_FAILED = 'STORAGE_CLEAR_FAILED',

    // Speech Errors
    STT_FAILED = 'STT_FAILED',
    TTS_FAILED = 'TTS_FAILED',
    MICROPHONE_PERMISSION_DENIED = 'MICROPHONE_PERMISSION_DENIED',

    // OCR Errors
    OCR_FAILED = 'OCR_FAILED',
    IMAGE_INVALID = 'IMAGE_INVALID',

    // Validation Errors
    VALIDATION_FAILED = 'VALIDATION_FAILED',
    INVALID_INPUT = 'INVALID_INPUT',

    // Network Errors
    NETWORK_ERROR = 'NETWORK_ERROR',
    TIMEOUT = 'TIMEOUT',

    // General Errors
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
